import { useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import heroGrad from '../assets/hero-grad-clean.png';
import heroGradCutout from '../assets/hero-grad-transparent.png';
import BrandLogo from '../components/common/BrandLogo';
import { GradientShimmer } from '@/components/ui/gradient-shimmer';
import {
  ChevronDown, CheckCircle, Shield, Zap, Play,
  FileText, BookOpen, GraduationCap, Award, PenTool,
  Sparkles, Quote, ArrowRight, Phone, Users, Clock, Target,
  BadgeCheck, Mail
} from 'lucide-react';

const heroFeatures = [
  { title: 'Local Context', desc: 'Built for Ghanaian curricula', icon: GraduationCap },
  { title: 'Quality Guards', desc: 'Accuracy checks before export', icon: Shield },
  { title: 'Fast Drafts', desc: 'From brief to paper in minutes', icon: Zap },
];

const services = [
  { title: 'Research Papers', desc: 'Undergraduate to journal-ready drafts with local academic context.', icon: FileText, tone: 'bg-[#2563eb]' },
  { title: 'Thesis Support', desc: 'Chapter-by-chapter structure for proposals through defense prep.', icon: GraduationCap, tone: 'bg-[#3b82f6]' },
  { title: 'Literature Review', desc: 'Systematic and narrative reviews grounded in African sources.', icon: BookOpen, tone: 'bg-[#1d4ed8]' },
  { title: 'Editing & Cite', desc: 'Grammar, structure, citations, and university formatting.', icon: Sparkles, tone: 'bg-[#60a5fa]' },
];

const offerings = [
  { title: 'Complete Paper', meta: 'End-to-end generation', price: 'GHS 250', tag: 'Per paper', icon: FileText },
  { title: 'Standard Plan', meta: 'Assisted writing monthly', price: 'GHS 120', tag: 'Monthly', icon: PenTool },
  { title: 'Premium Plan', meta: 'Thesis + priority review', price: 'GHS 200', tag: 'Monthly', icon: Award },
  { title: 'Literature Mode', meta: 'Source-grounded reviews', price: 'Included', tag: 'Premium', icon: BookOpen },
  { title: 'Citation Pack', meta: 'APA · MLA · Chicago · Harvard', price: 'Included', tag: 'All plans', icon: BadgeCheck },
  { title: 'University Templates', meta: 'KNUST · UG · UCC · UPSA', price: 'Included', tag: 'All plans', icon: GraduationCap },
];

const reasons = [
  { num: '01', title: 'Profile the right draft', desc: 'Brief your topic, level, and deadline — ResearchPadi maps Ghanaian university expectations.' },
  { num: '02', title: 'Write with academic guardrails', desc: 'Citations, structure, and quality checks stay connected inside one workspace.' },
  { num: '03', title: 'Submit with confidence', desc: 'Export Word or PDF ready for supervisors, departments, and journal formats.' },
];

const pricingPlans = [
  {
    name: 'Complete Paper',
    price: 'GHS 250',
    period: '/paper',
    desc: 'Full end-to-end AI paper generation',
    features: ['Complete paper written for you', 'AI writing + quality guards', 'APA/MLA/Chicago/Harvard', 'University templates', 'AI/human supervisor review'],
    cta: 'Order a Paper',
    highlighted: false,
  },
  {
    name: 'Standard',
    price: 'GHS 120',
    period: '/month',
    desc: 'Assisted writing for regular students',
    features: ['AI writing assist', 'All citation formats', 'All university templates', 'Quality guards', 'Email support'],
    cta: 'Start Standard',
    highlighted: true,
  },
  {
    name: 'Premium',
    price: 'GHS 200',
    period: '/month',
    desc: 'Assisted writing with full features',
    features: ['Everything in Standard', 'Priority AI/human supervisors', 'Thesis/dissertation mode', 'Literature review AI', 'Priority support'],
    cta: 'Start Premium',
    highlighted: false,
  },
];

const testimonials = [
  { name: 'Akosua M.', institution: 'Public University, Ghana', text: 'ResearchPadi changed how I approach academic writing. The AI understands my curriculum better than any generic tool I have tried.', role: 'Student', initials: 'AM' },
  { name: 'Kwame A.', institution: 'Technical University, Ghana', text: 'My supervisor was impressed by my literature review. ResearchPadi found local journals I never knew existed.', role: 'Student', initials: 'KA' },
  { name: 'Efua B.', institution: 'Public University, Ghana', text: 'The quality guards and supervisor review are incredible. My drafts came back polished and ready to submit.', role: 'Student', initials: 'EB' },
];

const faqs = [
  { q: 'What makes ResearchPadi different from ChatGPT?', a: 'ResearchPadi is trained specifically on Ghanaian academic standards, curricula, and local sources. It understands university formatting, prioritizes African journals, and keeps your draft inside a research workspace — not a generic chat thread.' },
  { q: 'Is the content really plagiarism-free?', a: 'Yes. Every paper generated by ResearchPadi is original. We also include a plagiarism scanner that checks against global databases and local academic repositories before you submit.' },
  { q: 'Which universities does ResearchPadi support?', a: 'We support Ghanaian tertiary institutions including KNUST, University of Ghana, UCC, UPSA, GIMPA, Ashesi, Technical Universities, and more.' },
  { q: 'Can I use ResearchPadi for my thesis or dissertation?', a: 'Yes. Premium includes thesis mode with chapter-by-chapter writing, advanced literature review AI, and reports suitable for postgraduate submissions.' },
  { q: 'How accurate are the citations?', a: 'Citations are cross-referenced against academic databases. We support APA, MLA, Chicago, and Harvard, tuned for Ghanaian and African sources.' },
];

export default function Landing() {
  const navigate = useNavigate();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  useEffect(() => {
    const nodes = document.querySelectorAll('.reveal');
    if (!nodes.length) return;
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.14, rootMargin: '0px 0px -8% 0px' }
    );
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  const scrollTo = (id: string) => {
    setMobileMenuOpen(false);
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="flex flex-col min-h-screen bg-white text-[#0f172a]">
      {/* Nav */}
      <nav className="sticky top-0 z-50 bg-white/90 backdrop-blur-xl border-b border-[#e2e8f0]">
        <div className="relative w-full px-3 sm:px-4 h-[72px] flex items-center justify-between gap-3">
          <BrandLogo
            onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            markClassName="h-10 w-auto"
            className="shrink-0"
          />

          <div className="hidden lg:flex items-center gap-8 absolute left-1/2 -translate-x-1/2">
            {[
              { label: 'Home', id: 'top' },
              { label: 'About', id: 'about' },
              { label: 'Services', id: 'services' },
              { label: 'Pricing', id: 'pricing' },
              { label: 'FAQs', id: 'faqs' },
            ].map((item) => (
              <button
                key={item.id}
                onClick={() => item.id === 'top' ? window.scrollTo({ top: 0, behavior: 'smooth' }) : scrollTo(item.id)}
                className="text-[13px] font-semibold text-[#64748b] hover:text-[#2563eb] transition"
              >
                {item.label}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-3 shrink-0">
            <button onClick={() => navigate('/login')} className="hidden md:inline text-[13px] font-semibold text-[#64748b] hover:text-[#0f172a]">
              Log in
            </button>
            <button onClick={() => navigate('/login')} className="hidden md:inline-flex btn-primary px-4 py-2.5 text-[13px] items-center gap-2">
              <Phone size={14} /> Start writing
            </button>
            <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="lg:hidden p-2 text-[#0f172a]" aria-label="Menu">
              {mobileMenuOpen ? '×' : '☰'}
            </button>
          </div>
        </div>

        {mobileMenuOpen && (
          <div className="lg:hidden border-t border-[#e2e8f0] bg-white px-3 sm:px-4 py-4 space-y-2">
            {['About', 'Services', 'Pricing', 'FAQs'].map((label) => (
              <button key={label} onClick={() => scrollTo(label.toLowerCase())} className="block w-full text-left py-2 text-sm font-semibold text-[#64748b]">
                {label}
              </button>
            ))}
            <button onClick={() => navigate('/login')} className="btn-primary w-full py-2.5 text-sm mt-2 md:hidden">Log in / Start writing</button>
          </div>
        )}
      </nav>

      {/* Hero */}
      <section className="relative bg-white overflow-visible sm:pb-28">
        {/* Visual hero plane — cutout base sits on this block's bottom edge */}
        <div className="relative overflow-visible">
          <div className="absolute inset-0 pointer-events-none" style={{
            background: 'radial-gradient(ellipse 45% 50% at 90% 20%, rgba(37,99,235,.08), transparent), radial-gradient(ellipse 40% 45% at 5% 85%, rgba(219,234,254,.55), transparent)',
          }} />

          <div className="relative max-w-6xl mx-auto px-5 sm:px-8 pt-10 sm:pt-20 lg:pt-24">
            <div className="grid lg:grid-cols-2 gap-0 lg:gap-8 items-start">
              <div className="text-[#0f172a] z-10 pb-2 sm:pb-6">
                <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#64748b] mb-3 sm:mb-4 fade-up">Academic writing workspace</p>
                <h1 className="text-4xl sm:text-5xl lg:text-[3.4rem] font-extrabold leading-[1.05] mb-4 sm:mb-5 fade-up fade-up-delay">
                  <span className="block mb-1">
                    <GradientShimmer
                      gradient="bay"
                      duration={1.6}
                      spread={2.4}
                      angle={105}
                      pauseBetween={1200}
                      baseColor="rgba(15,23,42,0.45)"
                      className="text-4xl sm:text-5xl lg:text-[3.4rem] font-extrabold tracking-tight"
                    >
                      ResearchPadi
                    </GradientShimmer>
                  </span>
                  Connecting ideas,<br />building papers.
                </h1>
                <p className="text-sm sm:text-base text-[#64748b] leading-relaxed max-w-md mb-6 sm:mb-8 fade-up fade-up-delay-2">
                  The AI writing platform built for Ghanaian students — drafts, citations, and quality checks in one calm workspace.
                </p>
                <div className="flex flex-col sm:flex-row gap-3 fade-up fade-up-delay-3">
                  <button onClick={() => navigate('/login')} className="btn-primary px-6 py-3.5 text-sm inline-flex items-center justify-center gap-2">
                    Get started <ArrowRight size={16} />
                  </button>
                  <button onClick={() => scrollTo('how')} className="border border-[#cbd5e1] text-[#0f172a] px-6 py-3.5 rounded-xl text-sm font-bold inline-flex items-center justify-center gap-2 hover:bg-[#f4f7fc] transition">
                    <Play size={14} fill="currentColor" /> Learn more
                  </button>
                </div>
              </div>

              {/* Height reserved for the bottom-pinned cutout (keeps copy clear) */}
              <div className="h-[250px] sm:h-[360px] lg:h-[480px]" aria-hidden />
            </div>
          </div>

          {/* Cutout: base flush to hero edge on every breakpoint */}
          <div className="pointer-events-none absolute inset-x-0 bottom-0 z-[1] flex justify-center px-5 sm:px-8 lg:justify-end lg:pr-[max(2rem,calc((100%-72rem)/2+2rem))] fade-up fade-up-delay-2">
            <img
              src={heroGradCutout}
              alt="Graduate celebrating academic success"
              className="block w-full max-w-[260px] sm:max-w-sm lg:max-w-md h-[250px] sm:h-[380px] lg:h-[540px] object-contain object-bottom drop-shadow-2xl"
            />
          </div>

          {/* Soft wash at the hero base — light, not heavy */}
          <div
            className="pointer-events-none absolute inset-x-0 bottom-0 z-[2] h-20 sm:h-28"
            style={{ background: 'linear-gradient(to top, #ffffff 0%, rgba(255,255,255,0.7) 35%, transparent 100%)' }}
          />
        </div>

        {/* Feature cards sit on / below the hero edge */}
        <div className="relative z-10 -mt-2 px-5 sm:px-8 sm:absolute sm:inset-x-0 sm:bottom-0 sm:mt-0 sm:translate-y-1/2">
          <div className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4">
            {heroFeatures.map((item, i) => {
              const Icon = item.icon;
              return (
                <div key={item.title} className={`bg-white rounded-2xl p-4 sm:p-5 shadow-xl border border-[#e2e8f0] reveal reveal-delay-${i + 1}`}>
                  <div className="w-10 h-10 rounded-xl bg-[#dbeafe] text-[#2563eb] grid place-items-center mb-3">
                    <Icon size={18} />
                  </div>
                  <p className="font-bold text-[#0f172a] text-sm mb-1">{item.title}</p>
                  <p className="text-xs text-[#64748b]">{item.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* About / stats */}
      <section id="about" className="pt-12 sm:pt-36 pb-20 sm:pb-28 bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8 grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          <div className="relative reveal is-visible">
            <div className="rounded-[1.75rem] overflow-hidden bg-[#dbeafe]">
              <img src={heroGrad} alt="Graduate celebrating academic success" className="w-full h-[280px] sm:h-[360px] object-cover object-[center_20%]" />
            </div>
            <div className="absolute left-3 top-3 sm:-left-2 sm:top-8 bg-white rounded-2xl px-3 py-2.5 shadow-xl flex items-center gap-2">
              <div className="w-8 h-8 rounded-xl bg-[#dbeafe] text-[#2563eb] grid place-items-center"><Zap size={14} /></div>
              <div>
                <p className="text-[11px] font-bold text-[#0f172a]">Fast Drafts</p>
                <p className="text-[10px] text-[#64748b]">From brief to paper in minutes</p>
              </div>
            </div>
            <div className="absolute -bottom-4 right-3 sm:-bottom-5 sm:right-6 bg-[#2563eb] text-white rounded-2xl px-4 py-3 sm:px-5 sm:py-4 shadow-xl">
              <p className="text-xl sm:text-2xl font-extrabold">Built for GH</p>
              <p className="text-[10px] sm:text-xs text-white/80">University-ready templates</p>
            </div>
          </div>

          <div className="reveal reveal-delay-1">
            <p className="eyebrow mb-3">About ResearchPadi</p>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#0f172a] leading-tight mb-4">
              Nurturing writers,<br />fueling research.
            </h2>
            <p className="text-sm text-[#64748b] leading-relaxed mb-8 max-w-md">
              Generic AI was not built for Ghanaian universities. ResearchPadi keeps drafts, citations, and quality checks connected from brief to submission.
            </p>
            <div className="grid grid-cols-2 gap-4 mb-8">
              <div className="rounded-2xl bg-[#f4f7fc] p-5">
                <p className="text-2xl font-extrabold text-[#2563eb]">10k+</p>
                <p className="text-xs text-[#64748b] mt-1">Students supported</p>
              </div>
              <div className="rounded-2xl bg-[#f4f7fc] p-5">
                <p className="text-2xl font-extrabold text-[#2563eb]">4+</p>
                <p className="text-xs text-[#64748b] mt-1">Citation formats</p>
              </div>
            </div>
            <button onClick={() => navigate('/login')} className="btn-primary px-5 py-3 text-sm inline-flex items-center gap-2">
              Learn more <ArrowRight size={15} />
            </button>
          </div>
        </div>
      </section>

      {/* Services */}
      <section id="services" className="py-20 sm:py-28 bg-[#f4f7fc]">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="text-center max-w-2xl mx-auto mb-12 reveal">
            <p className="eyebrow mb-3">Services</p>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#0f172a]">
              Tailoring papers for excellence.
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {services.map((service, i) => {
              const Icon = service.icon;
              return (
                <button
                  key={service.title}
                  onClick={() => scrollTo('pricing')}
                  className={`${service.tone} text-white rounded-2xl p-6 text-left min-h-[220px] flex flex-col justify-between hover:-translate-y-1 transition reveal reveal-delay-${(i % 4) + 1}`}
                >
                  <div className="w-11 h-11 rounded-xl bg-white/15 grid place-items-center">
                    <Icon size={20} />
                  </div>
                  <div>
                    <h3 className="text-lg font-extrabold mb-2">{service.title}</h3>
                    <p className="text-sm text-white/80 leading-relaxed">{service.desc}</p>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      </section>

      {/* Offerings grid (job-card style) */}
      <section className="py-20 sm:py-28 bg-gradient-to-b from-[#dbeafe]/60 to-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="text-center max-w-2xl mx-auto mb-12 reveal">
            <p className="eyebrow mb-3">Ready to write</p>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#0f172a]">
              Plans and tools ready to apply.
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {offerings.map((item, i) => {
              const Icon = item.icon;
              return (
                <div key={item.title} className={`bg-white rounded-2xl border border-[#e2e8f0] p-5 hover:shadow-lg hover:-translate-y-0.5 transition reveal reveal-delay-${(i % 3) + 1}`}>
                  <div className="flex items-start justify-between mb-4">
                    <div className="w-11 h-11 rounded-xl bg-[#dbeafe] text-[#2563eb] grid place-items-center">
                      <Icon size={18} />
                    </div>
                    <span className="text-[10px] font-bold uppercase tracking-wider text-[#2563eb] bg-[#dbeafe] px-2.5 py-1 rounded-lg">{item.tag}</span>
                  </div>
                  <h3 className="font-bold text-[#0f172a] mb-1">{item.title}</h3>
                  <p className="text-xs text-[#64748b] mb-4">{item.meta}</p>
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-extrabold text-[#0f172a]">{item.price}</p>
                    <button onClick={() => navigate('/login')} className="text-xs font-bold text-[#2563eb] hover:underline inline-flex items-center gap-1">
                      Apply now <ArrowRight size={12} />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Why choose us */}
      <section id="how" className="py-20 sm:py-28 bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8 grid lg:grid-cols-2 gap-12 items-center">
          <div className="grid grid-cols-2 gap-3 reveal">
            {[Users, Target, Clock, BadgeCheck].map((Icon, i) => (
              <div key={i} className={`rounded-2xl p-8 ${i % 2 === 0 ? 'bg-[#2563eb] text-white' : 'bg-[#dbeafe] text-[#1e3a8a]'} min-h-[140px] flex flex-col justify-between`}>
                <Icon size={22} />
                <p className="text-sm font-bold">{['Student-first', 'Source-aware', 'Fast turnaround', 'Export-ready'][i]}</p>
              </div>
            ))}
          </div>
          <div className="reveal reveal-delay-1">
            <p className="eyebrow mb-3">Why ResearchPadi</p>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#0f172a] leading-tight mb-8">
              Finding the right draft,<br />every time.
            </h2>
            <div className="space-y-5">
              {reasons.map((item) => (
                <div key={item.num} className="flex gap-4">
                  <span className="text-sm font-extrabold text-[#2563eb] shrink-0">{item.num}</span>
                  <div>
                    <h3 className="font-bold text-[#0f172a] mb-1">{item.title}</h3>
                    <p className="text-sm text-[#64748b] leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Banner CTA */}
      <section className="relative py-24 sm:py-28 overflow-hidden">
        <img src={heroGrad} alt="" className="absolute inset-0 w-full h-full object-cover object-[center_15%]" />
        <div className="absolute inset-0 bg-[#1e3a8a]/80" />
        <div className="relative max-w-3xl mx-auto px-5 text-center text-white reveal">
          <h2 className="text-3xl sm:text-5xl font-extrabold leading-tight mb-4">
            Shaping futures, one paper at a time.
          </h2>
          <p className="text-sm text-white/75 mb-8 max-w-lg mx-auto">
            Join Ghanaian students producing clearer, better-cited academic work.
          </p>
          <button onClick={() => navigate('/login')} className="bg-white text-[#2563eb] px-7 py-3.5 rounded-xl text-sm font-bold inline-flex items-center gap-2 hover:bg-[#dbeafe] transition">
            Start writing free <ArrowRight size={16} />
          </button>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 sm:py-28 bg-[#f4f7fc]">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="text-center max-w-xl mx-auto mb-12 reveal">
            <p className="eyebrow mb-3">Pricing</p>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#0f172a]">Simple plans. Clear results.</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-5 max-w-5xl mx-auto">
            {pricingPlans.map((plan, i) => (
              <div
                key={plan.name}
                className={`rounded-2xl p-7 transition hover:-translate-y-1 reveal reveal-delay-${i + 1} ${
                  plan.highlighted
                    ? 'bg-[#2563eb] text-white shadow-xl'
                    : 'bg-white border border-[#e2e8f0]'
                }`}
              >
                {plan.highlighted && (
                  <div className="inline-flex items-center gap-1.5 bg-white/15 text-white text-[10px] font-bold px-3 py-1 rounded-lg mb-4 uppercase tracking-wider">
                    <Zap className="w-3 h-3" /> Most popular
                  </div>
                )}
                <h3 className={`text-lg font-extrabold mb-1 ${plan.highlighted ? 'text-white' : 'text-[#0f172a]'}`}>{plan.name}</h3>
                <p className={`text-xs mb-5 ${plan.highlighted ? 'text-white/70' : 'text-[#64748b]'}`}>{plan.desc}</p>
                <div className="flex items-baseline gap-1 mb-6">
                  <span className={`text-3xl font-extrabold ${plan.highlighted ? 'text-white' : 'text-[#0f172a]'}`}>{plan.price}</span>
                  <span className={`text-sm ${plan.highlighted ? 'text-white/60' : 'text-[#64748b]'}`}>{plan.period}</span>
                </div>
                <ul className="space-y-3 mb-7">
                  {plan.features.map((feat) => (
                    <li key={feat} className="flex items-start gap-2.5">
                      <CheckCircle className={`w-4 h-4 shrink-0 mt-0.5 ${plan.highlighted ? 'text-white/70' : 'text-[#2563eb]'}`} />
                      <span className={`text-sm ${plan.highlighted ? 'text-white/85' : 'text-[#64748b]'}`}>{feat}</span>
                    </li>
                  ))}
                </ul>
                <button
                  onClick={() => navigate('/login')}
                  className={`w-full py-3 rounded-xl font-bold text-sm transition ${
                    plan.highlighted ? 'bg-white text-[#2563eb] hover:bg-[#dbeafe]' : 'btn-primary'
                  }`}
                >
                  {plan.cta}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 sm:py-28 bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="text-center mb-12 reveal">
            <p className="eyebrow mb-3">Client feedback</p>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#0f172a]">What students say</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {testimonials.map((t, i) => (
              <blockquote key={t.initials} className={`rounded-2xl border border-[#e2e8f0] bg-[#f4f7fc] p-6 reveal reveal-delay-${i + 1}`}>
                <Quote className="w-7 h-7 text-[#bfdbfe] mb-4" />
                <p className="text-sm text-[#0f172a] leading-relaxed mb-6">“{t.text}”</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-[#2563eb] text-white text-xs font-bold grid place-items-center">{t.initials}</div>
                  <div>
                    <p className="text-sm font-bold text-[#0f172a]">{t.name}</p>
                    <p className="text-xs text-[#64748b]">{t.role} · {t.institution}</p>
                  </div>
                </div>
              </blockquote>
            ))}
          </div>
        </div>
      </section>

      {/* Contact + FAQ */}
      <section id="faqs" className="py-20 sm:py-28 bg-[#f4f7fc]">
        <div className="max-w-6xl mx-auto px-5 sm:px-8 grid lg:grid-cols-2 gap-8 items-start">
          <div className="bg-[#1e3a8a] text-white rounded-[1.75rem] p-7 sm:p-8 reveal">
            <p className="text-xs font-bold uppercase tracking-[0.16em] text-white/60 mb-3">Contact</p>
            <h2 className="text-2xl sm:text-3xl font-extrabold mb-2">Ready to start your paper?</h2>
            <p className="text-sm text-white/70 mb-8">Create an account and brief your first draft in minutes.</p>
            <div className="space-y-3 mb-8">
              <div className="flex items-center gap-3 text-sm text-white/85"><Mail size={16} /> hello@researchpadi.com</div>
              <div className="flex items-center gap-3 text-sm text-white/85"><Phone size={16} /> Kumasi, Ghana</div>
            </div>
            <button onClick={() => navigate('/login')} className="bg-white text-[#1e3a8a] px-6 py-3.5 rounded-xl text-sm font-bold inline-flex items-center gap-2 hover:bg-[#dbeafe] transition">
              Start writing free <ArrowRight size={16} />
            </button>
          </div>

          <div className="reveal reveal-delay-1">
            <p className="eyebrow mb-3">FAQ</p>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-[#0f172a] mb-6">Frequently asked questions</h2>
            <div className="space-y-2">
              {faqs.map((faq, i) => (
                <div key={faq.q} className={`rounded-xl border bg-white transition ${openFaq === i ? 'border-[#bfdbfe]' : 'border-[#e2e8f0]'}`}>
                  <button onClick={() => setOpenFaq(openFaq === i ? null : i)} className="w-full flex items-center justify-between px-5 py-4 text-left">
                    <span className="text-sm font-bold text-[#0f172a] pr-4">{faq.q}</span>
                    <ChevronDown className={`w-4 h-4 text-[#64748b] shrink-0 transition-transform ${openFaq === i ? 'rotate-180' : ''}`} />
                  </button>
                  {openFaq === i && (
                    <div className="px-5 pb-4">
                      <p className="text-sm text-[#64748b] leading-relaxed">{faq.a}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Stats bar */}
      <section className="bg-[#2563eb] text-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8 py-10 grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
          {[
            ['10k+', 'Students'],
            ['4+', 'Citation styles'],
            ['99%', 'Original drafts'],
            ['GH', 'University templates'],
          ].map(([value, label]) => (
            <div key={label}>
              <p className="text-3xl font-extrabold">{value}</p>
              <p className="text-xs text-white/70 mt-1">{label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-[#0f172a] py-3 text-white">
        <div className="max-w-4xl mx-auto px-5 sm:px-8 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
            <BrandLogo onDark markClassName="h-5 w-auto" className="[&_span]:text-xs" />
            <span className="hidden sm:inline text-[#334155]">·</span>
            {['Services', 'Pricing', 'FAQs'].map((item) => (
              <button key={item} onClick={() => scrollTo(item.toLowerCase())} className="text-[10px] text-[#94a3b8] hover:text-white transition">
                {item}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-3 text-[10px] text-[#64748b]">
            <p>&copy; {new Date().getFullYear()} ResearchPadi · Kumasi</p>
            <span className="inline-flex items-center gap-1"><Shield size={9} className="text-[#059669]" /> SSL</span>
            <span className="inline-flex items-center gap-1"><CheckCircle size={9} className="text-[#059669]" /> GDPR</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
