import { useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import logo from '../assets/logo.svg';
import heroGrad from '../assets/hero-grad.png';
import {
  ChevronDown, CheckCircle, Shield, Zap,
  FileText, BookOpen, GraduationCap, Award, PenTool,
  Sparkles, Quote, ArrowRight
} from 'lucide-react';

const services = [
  { title: 'Research papers', desc: 'Undergraduate to journal-ready drafts with local academic context.', icon: FileText },
  { title: 'Essay writing', desc: 'Argumentative, expository, and coursework support that stays on-brief.', icon: PenTool },
  { title: 'Thesis & dissertation', desc: 'Chapter-by-chapter structure for proposals through defense prep.', icon: GraduationCap },
  { title: 'Literature review', desc: 'Systematic and narrative reviews grounded in African sources.', icon: BookOpen },
  { title: 'Assignment help', desc: 'Coursework, case studies, and lab reports matched to your course.', icon: Award },
  { title: 'Editing & proofreading', desc: 'Grammar, structure, citations, and university formatting.', icon: Sparkles },
];

const steps = [
  { num: '01', title: 'Brief your paper', desc: 'Share topic, level, and deadline. ResearchPadi maps Ghanaian university expectations.' },
  { num: '02', title: 'Generate a draft', desc: 'Get a structured, cited draft in minutes — not a generic chatbot dump.' },
  { num: '03', title: 'Review & refine', desc: 'Polish with quality guards, plagiarism checks, and formatting tools.' },
  { num: '04', title: 'Submit with confidence', desc: 'Export Word or PDF ready for KNUST, UG, UCC, and beyond.' },
];

const pricingPlans = [
  {
    name: 'Complete Paper',
    price: 'GHS 250',
    period: '/paper',
    desc: 'Full end-to-end AI paper generation',
    features: ['Complete paper written for you', 'AI writing + quality guards', 'APA/MLA/Chicago/Harvard', 'University templates', 'AI/human supervisor review'],
    cta: 'Order a Paper',
    highlighted: false,
  },
  {
    name: 'Standard',
    price: 'GHS 120',
    period: '/month',
    desc: 'Assisted writing for regular students',
    features: ['AI writing assist', 'All citation formats', 'All university templates', 'Quality guards', 'Email support'],
    cta: 'Start Standard',
    highlighted: true,
  },
  {
    name: 'Premium',
    price: 'GHS 200',
    period: '/month',
    desc: 'Assisted writing with full features',
    features: ['Everything in Standard', 'Priority AI/human supervisors', 'Thesis/dissertation mode', 'Literature review AI', 'Priority support'],
    cta: 'Start Premium',
    highlighted: false,
  },
];

const testimonials = [
  { name: 'Anonymous', institution: 'Public University, Ghana', text: 'ResearchPadi changed how I approach academic writing. The AI understands my curriculum better than any generic tool I have tried.', role: 'Student' },
  { name: 'Anonymous', institution: 'Technical University, Ghana', text: 'My supervisor was impressed by my literature review. ResearchPadi found local journals I never knew existed.', role: 'Student' },
  { name: 'Anonymous', institution: 'Public University, Ghana', text: 'The quality guards and supervisor review are incredible. My drafts came back polished and ready to submit.', role: 'Student' },
];

const faqs = [
  { q: 'What makes ResearchPadi different from ChatGPT?', a: 'ResearchPadi is trained specifically on Ghanaian academic standards, curricula, and local sources. It understands university formatting, prioritizes African journals, and keeps your draft inside a research workspace — not a generic chat thread.' },
  { q: 'Is the content really plagiarism-free?', a: 'Yes. Every paper generated by ResearchPadi is original. We also include a plagiarism scanner that checks against global databases and local academic repositories before you submit.' },
  { q: 'Which universities does ResearchPadi support?', a: 'We support Ghanaian tertiary institutions including KNUST, University of Ghana, UCC, UPSA, GIMPA, Ashesi, Technical Universities, and more.' },
  { q: 'Can I use ResearchPadi for my thesis or dissertation?', a: 'Yes. Premium includes thesis mode with chapter-by-chapter writing, advanced literature review AI, and reports suitable for postgraduate submissions.' },
  { q: 'How accurate are the citations?', a: 'Citations are cross-referenced against academic databases. We support APA, MLA, Chicago, and Harvard, tuned for Ghanaian and African sources.' },
];

export default function Landing() {
  const navigate = useNavigate();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    const nodes = document.querySelectorAll('.reveal');
    if (!nodes.length) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.14, rootMargin: '0px 0px -8% 0px' }
    );

    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  const scrollTo = (id: string) => {
    setMobileMenuOpen(false);
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="flex flex-col min-h-screen bg-white text-[#0f172a]">
      {/* Nav */}
      <nav className="fixed top-0 w-full z-50 bg-white/75 backdrop-blur-xl border-b border-[#e2e8f0]/70">
        <div className="max-w-6xl mx-auto px-5 sm:px-8 h-16 flex items-center justify-between">
          <button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="flex items-center gap-2.5 shrink-0" aria-label="ResearchPadi home">
            <img src={logo} alt="ResearchPadi" className="h-11 w-auto" />
          </button>

          <div className="hidden md:flex items-center gap-8">
            {[
              { label: 'Services', id: 'services' },
              { label: 'Pricing', id: 'pricing' },
              { label: 'FAQs', id: 'faqs' },
            ].map((item) => (
              <button key={item.id} onClick={() => scrollTo(item.id)} className="text-[13px] font-medium text-[#64748b] hover:text-[#0f172a] transition">
                {item.label}
              </button>
            ))}
          </div>

          <div className="hidden md:flex items-center gap-2.5">
            <button onClick={() => navigate('/login')} className="btn-ghost px-4 py-2 text-[13px]">Log in</button>
            <button onClick={() => navigate('/login')} className="btn-primary px-4 py-2 text-[13px]">Start writing</button>
          </div>

          <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="md:hidden p-2 text-[#0f172a]" aria-label="Menu">
            {mobileMenuOpen ? <span className="text-xl">&times;</span> : <span className="text-xl">&#9776;</span>}
          </button>
        </div>

        {mobileMenuOpen && (
          <div className="md:hidden bg-white border-t border-[#e2e8f0] px-5 py-4 space-y-2 shadow-lg">
            {[
              { label: 'Services', id: 'services' },
              { label: 'Pricing', id: 'pricing' },
              { label: 'FAQs', id: 'faqs' },
            ].map((item) => (
              <button key={item.id} onClick={() => scrollTo(item.id)} className="block w-full text-left text-sm font-medium text-[#64748b] py-2">
                {item.label}
              </button>
            ))}
            <div className="flex gap-2 pt-2">
              <button onClick={() => { setMobileMenuOpen(false); navigate('/login'); }} className="flex-1 btn-ghost py-2.5 text-sm">Log in</button>
              <button onClick={() => { setMobileMenuOpen(false); navigate('/login'); }} className="flex-1 btn-primary py-2.5 text-sm">Start writing</button>
            </div>
          </div>
        )}
      </nav>

      {/* Hero — brand left, portrait clear on the right */}
      <section className="relative pt-16 min-h-[88vh] lg:min-h-[92vh] overflow-hidden bg-[#1a2433]">
        <img
          src={heroGrad}
          alt=""
          className="absolute inset-0 w-full h-full object-cover object-[88%_12%] md:object-[92%_8%] lg:object-[95%_5%] hero-ken"
          style={{ transformOrigin: '80% 8%' }}
        />
        {/* Soft left panel so copy never sits on the face */}
        <div className="absolute inset-y-0 left-0 w-[88%] sm:w-[72%] md:w-[58%] lg:w-[48%] bg-gradient-to-r from-[#0f172a]/92 via-[#0f172a]/72 to-transparent" />
        {/* Subtle base wash into next section */}
        <div className="absolute inset-x-0 bottom-0 h-24 sm:h-28 bg-gradient-to-t from-[#f8fafc] to-transparent" />

        <div className="relative max-w-6xl mx-auto px-5 sm:px-8 min-h-[calc(88vh-4rem)] lg:min-h-[calc(92vh-4rem)] flex items-center py-16 sm:py-20">
          <div className="w-full max-w-[17.5rem] sm:max-w-[19rem] md:max-w-[22rem]">
            <p className="display text-4xl sm:text-5xl lg:text-[3.5rem] text-white leading-[0.95] mb-4 sm:mb-5 fade-up">
              ResearchPadi
            </p>
            <h1 className="text-lg sm:text-xl lg:text-2xl font-bold text-white leading-snug mb-3 sm:mb-4 tracking-tight fade-up fade-up-delay">
              Write papers your supervisors can trust.
            </h1>
            <p className="text-sm text-white/80 leading-relaxed mb-7 sm:mb-8 fade-up fade-up-delay-2">
              The academic writing workspace built for Ghanaian students — drafts, citations, and quality checks in one calm place.
            </p>
            <div className="flex flex-col gap-2.5 sm:flex-row sm:gap-3 fade-up fade-up-delay-3">
              <button onClick={() => navigate('/login')} className="bg-white text-[#1e3a5f] px-5 py-3 rounded-xl text-sm font-bold inline-flex items-center justify-center gap-2 hover:bg-[#e9eef5] hover:-translate-y-0.5 transition">
                Start your first paper <ArrowRight size={16} />
              </button>
              <button onClick={() => scrollTo('how')} className="border border-white/35 text-white px-5 py-3 rounded-xl text-sm font-bold bg-white/10 backdrop-blur-sm hover:bg-white/20 hover:-translate-y-0.5 transition">
                See how it works
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Trust strip */}
      <section className="border-y border-[#e2e8f0] bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8 py-5 flex flex-wrap items-center justify-between gap-4 text-[12px] font-medium text-[#64748b] trust-marquee reveal">
          <span className="inline-flex items-center gap-2"><Shield size={14} className="text-[#1e3a5f]" /> Plagiarism-aware drafts</span>
          <span className="inline-flex items-center gap-2"><FileText size={14} className="text-[#1e3a5f]" /> APA · MLA · Chicago · Harvard</span>
          <span className="inline-flex items-center gap-2"><GraduationCap size={14} className="text-[#1e3a5f]" /> KNUST · UG · UCC · UPSA</span>
          <span className="inline-flex items-center gap-2"><CheckCircle size={14} className="text-[#059669]" /> Built for Ghanaian curricula</span>
        </div>
      </section>

      {/* Services */}
      <section id="services" className="py-20 sm:py-28 bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="max-w-2xl mb-14 reveal">
            <p className="eyebrow mb-3">Services</p>
            <h2 className="display text-4xl sm:text-5xl text-[#0f172a] leading-tight mb-3">
              Everything you need to finish the paper.
            </h2>
            <p className="text-sm text-[#64748b] leading-relaxed">
              From first brief to final export — one workspace for the writing Ghanaian students actually do.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-10">
            {services.map((service, i) => {
              const Icon = service.icon;
              return (
                <button
                  key={service.title}
                  onClick={() => scrollTo('pricing')}
                  className={`group text-left reveal reveal-delay-${(i % 3) + 1}`}
                >
                  <div className="w-11 h-11 rounded-xl bg-[#e9eef5] text-[#1e3a5f] flex items-center justify-center mb-4 group-hover:bg-[#1e3a5f] group-hover:text-white transition-all duration-300 group-hover:-translate-y-0.5">
                    <Icon size={20} />
                  </div>
                  <h3 className="text-lg font-bold text-[#0f172a] mb-1.5 group-hover:text-[#2563eb] transition-colors">{service.title}</h3>
                  <p className="text-sm text-[#64748b] leading-relaxed">{service.desc}</p>
                </button>
              );
            })}
          </div>
        </div>
      </section>

      {/* Why */}
      <section className="py-20 sm:py-28 bg-[#f8fafc]">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-start">
            <div className="reveal">
              <p className="eyebrow mb-3">Why ResearchPadi</p>
              <h2 className="display text-4xl sm:text-5xl text-[#0f172a] leading-tight mb-4">
                Not a chat app with writing bolted on.
              </h2>
              <p className="text-sm text-[#64748b] leading-relaxed mb-8 max-w-md">
                Generic AI was not built for Ghanaian universities. ResearchPadi keeps drafts, citations, and quality checks connected from brief to submission.
              </p>
              <button onClick={() => navigate('/login')} className="btn-primary px-5 py-3 text-sm inline-flex items-center gap-2">
                Try it free <ArrowRight size={15} />
              </button>
            </div>

            <div className="space-y-0 border-t border-[#e2e8f0]">
              {[
                { aspect: 'Ghanaian academic context', rp: 'Trained on local curricula & standards' },
                { aspect: 'Citation formats', rp: 'APA, MLA, Chicago, Harvard — Ghana-ready' },
                { aspect: 'Quality guards', rp: 'Multi-layer review for accuracy & relevance' },
                { aspect: 'University templates', rp: 'KNUST, UG, UCC, UPSA, GIMPA' },
                { aspect: 'Student pricing', rp: 'From GHS 120/mo or GHS 250/paper' },
              ].map((row, i) => (
                <div key={row.aspect} className={`flex gap-4 py-5 border-b border-[#e2e8f0] reveal reveal-delay-${(i % 4) + 1}`}>
                  <CheckCircle className="w-5 h-5 text-[#2563eb] shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-bold text-[#0f172a]">{row.aspect}</p>
                    <p className="text-sm text-[#64748b] mt-0.5">{row.rp}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="py-20 sm:py-28 bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="text-center max-w-xl mx-auto mb-16 reveal">
            <p className="eyebrow mb-3">Workflow</p>
            <h2 className="display text-4xl sm:text-5xl text-[#0f172a] leading-tight">
              Four steps from brief to submission.
            </h2>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-10">
            {steps.map((step, i) => (
              <div key={step.num} className={`reveal reveal-delay-${i + 1}`}>
                <p className="display text-5xl text-[#e2e8f0] mb-3">{step.num}</p>
                <h3 className="text-base font-bold text-[#0f172a] mb-2">{step.title}</h3>
                <p className="text-sm text-[#64748b] leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 sm:py-28 bg-[#f8fafc]">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="text-center max-w-xl mx-auto mb-14 reveal">
            <p className="eyebrow mb-3">Pricing</p>
            <h2 className="display text-4xl sm:text-5xl text-[#0f172a] leading-tight mb-3">
              Simple plans. No surprises.
            </h2>
            <p className="text-sm text-[#64748b]">Start free, upgrade when you need more.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-5 max-w-5xl mx-auto">
            {pricingPlans.map((plan, i) => (
              <div
                key={plan.name}
                className={`rounded-2xl p-7 transition hover:-translate-y-1 reveal reveal-delay-${i + 1} ${
                  plan.highlighted
                    ? 'bg-[#1e3a5f] text-white shadow-xl'
                    : 'bg-white border border-[#e2e8f0] hover:shadow-lg'
                }`}
              >
                {plan.highlighted && (
                  <div className="inline-flex items-center gap-1.5 bg-white/10 text-white text-[10px] font-bold px-3 py-1 rounded-lg mb-4 uppercase tracking-wider">
                    <Zap className="w-3 h-3" /> Most popular
                  </div>
                )}
                <h3 className={`text-lg font-bold mb-1 ${plan.highlighted ? 'text-white' : 'text-[#0f172a]'}`}>{plan.name}</h3>
                <p className={`text-xs mb-5 ${plan.highlighted ? 'text-white/60' : 'text-[#64748b]'}`}>{plan.desc}</p>
                <div className="flex items-baseline gap-1 mb-6">
                  <span className={`text-3xl font-bold ${plan.highlighted ? 'text-white' : 'text-[#0f172a]'}`}>{plan.price}</span>
                  {plan.period && <span className={`text-sm ${plan.highlighted ? 'text-white/55' : 'text-[#64748b]'}`}>{plan.period}</span>}
                </div>
                <ul className="space-y-3 mb-7">
                  {plan.features.map((feat) => (
                    <li key={feat} className="flex items-start gap-2.5">
                      <CheckCircle className={`w-4 h-4 shrink-0 mt-0.5 ${plan.highlighted ? 'text-white/50' : 'text-[#2563eb]'}`} />
                      <span className={`text-sm ${plan.highlighted ? 'text-white/80' : 'text-[#64748b]'}`}>{feat}</span>
                    </li>
                  ))}
                </ul>
                <button
                  onClick={() => navigate('/login')}
                  className={`w-full py-3 rounded-xl font-bold text-sm transition ${
                    plan.highlighted
                      ? 'bg-white text-[#1e3a5f] hover:bg-[#e9eef5]'
                      : 'btn-primary'
                  }`}
                >
                  {plan.cta}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 sm:py-28 bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="text-center mb-14 reveal">
            <p className="eyebrow mb-3">Students</p>
            <h2 className="display text-4xl sm:text-5xl text-[#0f172a]">What writers say</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((t, i) => (
              <blockquote key={t.institution + t.text.slice(0, 20)} className={`relative reveal reveal-delay-${i + 1}`}>
                <Quote className="w-7 h-7 text-[#e2e8f0] mb-4" />
                <p className="text-[15px] text-[#0f172a] leading-relaxed mb-6">“{t.text}”</p>
                <footer>
                  <p className="text-sm font-bold text-[#0f172a]">{t.name}</p>
                  <p className="text-xs text-[#64748b] mt-0.5">{t.role} · {t.institution}</p>
                </footer>
              </blockquote>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faqs" className="py-20 sm:py-28 bg-[#f8fafc]">
        <div className="max-w-2xl mx-auto px-5 sm:px-8">
          <div className="text-center mb-12 reveal">
            <p className="eyebrow mb-3">FAQ</p>
            <h2 className="display text-4xl sm:text-5xl text-[#0f172a]">Questions, answered</h2>
          </div>

          <div className="space-y-2">
            {faqs.map((faq, i) => (
              <div key={faq.q} className={`rounded-xl border bg-white transition reveal reveal-delay-${(i % 4) + 1} ${openFaq === i ? 'border-[#cbd5e1]' : 'border-[#e2e8f0] hover:border-[#cbd5e1]'}`}>
                <button onClick={() => setOpenFaq(openFaq === i ? null : i)} className="w-full flex items-center justify-between px-5 py-4 text-left">
                  <span className="text-sm font-bold text-[#0f172a] pr-4">{faq.q}</span>
                  <ChevronDown className={`w-4 h-4 text-[#64748b] shrink-0 transition-transform duration-200 ${openFaq === i ? 'rotate-180' : ''}`} />
                </button>
                {openFaq === i && (
                  <div className="px-5 pb-4">
                    <p className="text-sm text-[#64748b] leading-relaxed">{faq.a}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section id="contact" className="py-24 sm:py-32 bg-[#1e3a5f] relative overflow-hidden">
        <div className="absolute inset-0 opacity-30 pointer-events-none" style={{
          background: 'radial-gradient(ellipse 60% 50% at 50% 0%, rgba(37,99,235,.35), transparent)',
        }} />
        <div className="max-w-2xl mx-auto px-5 sm:px-8 text-center relative z-10 reveal">
          <h2 className="display text-4xl sm:text-5xl text-white leading-tight mb-4">
            Ready to write your best paper?
          </h2>
          <p className="text-sm text-white/65 max-w-md mx-auto mb-8 leading-relaxed">
            Join Ghanaian students producing clearer, better-cited academic work — starting free today.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <button onClick={() => navigate('/login')} className="bg-white text-[#1e3a5f] px-7 py-3.5 rounded-xl font-bold text-sm hover:bg-[#e9eef5] hover:-translate-y-0.5 transition">
              Start writing for free
            </button>
            <button onClick={() => navigate('/login')} className="border border-white/25 text-white px-7 py-3.5 rounded-xl font-bold text-sm hover:bg-white/10 hover:-translate-y-0.5 transition">
              Sign in
            </button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-[#0f172a] pt-16 pb-8">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-10 mb-12">
            <div className="col-span-2 md:col-span-1">
              <img src={logo} alt="ResearchPadi" className="h-14 w-auto mb-4 brightness-0 invert opacity-90" />
              <p className="text-sm text-[#64748b] leading-relaxed max-w-xs">
                Ghana's academic writing workspace. Built for every tertiary student.
              </p>
            </div>
            <div>
              <h4 className="text-xs font-bold text-[#94a3b8] uppercase tracking-wider mb-4">Product</h4>
              <ul className="space-y-2.5">
                {['Services', 'Pricing', 'FAQs'].map((item) => (
                  <li key={item}>
                    <button onClick={() => scrollTo(item.toLowerCase())} className="text-sm text-[#64748b] hover:text-white transition">{item}</button>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="text-xs font-bold text-[#94a3b8] uppercase tracking-wider mb-4">Company</h4>
              <ul className="space-y-2.5">
                {['About', 'Blog', 'Careers'].map((item) => (
                  <li key={item}><span className="text-sm text-[#64748b]">{item}</span></li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="text-xs font-bold text-[#94a3b8] uppercase tracking-wider mb-4">Legal</h4>
              <ul className="space-y-2.5">
                {['Privacy Policy', 'Terms of Service'].map((item) => (
                  <li key={item}><span className="text-sm text-[#64748b]">{item}</span></li>
                ))}
              </ul>
            </div>
          </div>

          <div className="border-t border-white/10 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
            <p className="text-xs text-[#475569]">&copy; {new Date().getFullYear()} ResearchPadi by AbusuaITLabs, Kumasi, Ghana.</p>
            <div className="flex items-center gap-4 text-xs text-[#475569]">
              <span className="inline-flex items-center gap-1.5"><Shield className="w-3.5 h-3.5 text-[#059669]" /> SSL Encrypted</span>
              <span className="inline-flex items-center gap-1.5"><CheckCircle className="w-3.5 h-3.5 text-[#059669]" /> GDPR Compliant</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
